#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Respect the shebang and mark file as executable

import os
import base64

import importlib.util
import sys
import shutil


def import_from_path(module_name, file_path):
    spec = importlib.util.spec_from_file_location(module_name, file_path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module

def main():
    shutil.copyfile("/app/meson.build", "/build/meson.build")
    # send the file using:
    # base64 main.f ; echo "@"
    print("------------------------Welcome to FROST------------------------")
    print("-------AKA Fortran Runtime for On-demand Simulation Tasks-------")
    print("Fortran Subroutines:")
    base64file = ""
    while True:
         a = input().strip()
         if "@" == a:
             break
         base64file += a

    fortranfile = base64.b64decode(base64file).decode()
    with open("/build/subroutine.f90", "w+") as f:
        f.write(fortranfile)

    print("Routine Selection:")
    simulation_sel = int(input().strip())

    os.chdir("/build/")
    os.system("meson setup /build/build && cd /build/build && meson compile && meson test")
    subr = import_from_path("subr","/build/build/subr.cpython-312-x86_64-linux-gnu.so")

    result = subr.run_simulation(simulation_sel)
    print("Here are your results")
    print(result)
    exit(0)

if __name__ == '__main__':
    main()
